# Get Queues
GET http://localhost:3000/api/queues/all

# Create Queues
POST http://localhost:3000/api/queues/add
Content-Type: application/json

{
  "name": "myqueue"
}

# Get Messages in Queue
GET http://localhost:3000/api/queues/64f327bb7ebd0f32d0cf8056/messages

# Produce Message
#*************************************************************************
POST http://localhost:3000/api/messages/produce
Content-Type: application/json

{
  "queueId": "64f327bb7ebd0f32d0cf8056",
  "body": "hell world 1"
}

# Produce Message
POST http://localhost:3000/api/messages/produce
Content-Type: application/json

{
  "queueId": "64f327bb7ebd0f32d0cf8056",
  "body": "hell world 2"
}

# Produce Message
POST http://localhost:3000/api/messages/produce
Content-Type: application/json

{
  "queueId": "64f327bb7ebd0f32d0cf8056",
  "body": "hell world 3"
}

#*************************************************************************
# Consume Message
POST http://localhost:3000/api/messages/consume
Content-Type: application/json

{
  "queueId": "64f327bb7ebd0f32d0cf8056"
}

#*************************************************************************
# Delete Message
DELETE http://localhost:3000/api/messages/64fb093a7a3642739cb7aec3/delete
Content-Type: application/json
